name: Run on self-hosted runner

on:
  push:
    branches: [ "master" ]

jobs:
  run-code:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - run: mvn clean install
      - run: java -jar target/shoe-ShoppingCart-0.0.1-SNAPSHOT.jar
