name: Run on self-hosted runner

on:
  push:
    branches: [ "master" ]

jobs:
  run-code:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run your code
        run: |
          echo "Running code from repo"
          pwd
